
class UserDoesNotExist(Exception):
    ...

class UserLowTrust(Exception):
    ...

class UserWithNameExists(Exception):
    ...

class UserWrongPassword(Exception):
    ...

class UserNewPasswordIsOldPassword(Exception):
    ...

class UserNewPasswordDoesNotMatch(Exception):
    ...

class UserHasPendingRequest(Exception):
    ...

class UsernameAlreadyTaken(Exception):
    ...

class TokenInvalid(Exception):
    ...
